---
- name: Install Extra Tooling
  hosts: localhost
  become: true # Necessary to run with root privileges
  tasks:
    - name: Install Zenith (System Resource Monitor)
      community.general.pacman:
        name: zenith
        state: present
        update_cache: true

    - name: Install Cull (Disk Usage Analyzer)
      yay:
        name: cull-bin
        state: present
