---
- name: Install Core Tooling
  hosts: localhost
  become: true # Necessary to run with root privileges
  tasks:
    - name: Install Yazi
      community.general.pacman:
        name: yazi
        state: present
        update_cache: true

    - name: Install MediaInfo
      community.general.pacman:
        name: mediainfo
        state: present
        update_cache: true

    - name: Install ImageMagick
      community.general.pacman:
        name: imagemagick
        state: present
        update_cache: true

    - name: Install Yazi MediaInfo Plug
      ansible.builtin.command: >
        ya pkg add boydaihungst/mediainfo
      changed_when: true
