---
- name: Install Core Tooling
  hosts: localhost
  become: true  # Necessary to run with root privileges
  tasks:
    - name: Install Kitty
      community.general.pacman:
        name: kitty
        state: present
        update_cache: true
    - name: Install Tmux
      community.general.pacman:
        name: tmux
        state: present
        update_cache: true
    - name: Install Yazi
      community.general.pacman:
        name: yazi
        state: present
        update_cache: true
